config/routes.rb
Ribbot::Application.routes.draw do

  resources :posts do
    resources :comments
  end
  resources :forums
  resources :votes
  resources :users do
    member do
      put :password_reset
    end
    collection do
      post :create_with_forum
    end
  end
  resources :participations do
    member do
      put :ban
      put :unban
      put :hide
    end
  end
  resources :themes
  resources :pages
  
  namespace :account do
    resources :comments
    resources :posts
    resource  :profile
    resources :users
    resources :settings
    resources :tags do
      post :sort, :on => :collection
    end
    resources :pages do
      post :sort, :on => :collection
    end
    resources :themes do
      post :install, :on => :member
      post :uninstall, :on => :collection
    end
    resource :ownership
    resource :domain
  end
  
  namespace :superuser do
    resources :forums
  end
  
  resources :verifications
  resources :password_resets
  resources :sessions

  match 'signin' => "sessions#new"
  match 'signout' => "sessions#destroy", :via => :delete
  match 'features' => 'static#features'
  match 'pricing' => 'static#pricing'
  
  constraints(Subdomain) do
    match '/' => 'posts#index'  
  end
  
  root :to => 'users#new'
  

end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongo::Voteable
  acts_as_nested_set
  include MarkdownProcessor
  
  field :text, type: String
  field :html, type: String
  field :deleted, type: Boolean, default: false
  field :ranking, type: Float, default: 0.0
  
  index :ranking
  index :'votes.point'

  belongs_to :user, index: true
  belongs_to :post, index: true
  belongs_to :forum, index: true
  
  validates_presence_of :text, :user, :post, :forum
  validate :user_is_not_banned
  
  voteable self, :up => +1, :down => -1
  
  before_save  :process_markdown
  after_create  :create_participation
  after_create  :inc_comment_count
  after_destroy :dec_comment_count
  
  attr_protected :parent_id
  
  def create_participation
    forum.add_member(user)
  end
  
  def inc_comment_count
    post.inc(:comment_count, 1)
  end
  
  def dec_comment_count
    post.inc(:comment_count, -1)
  end
  
  def user_is_not_banned
    errors.add(:base, "You can no longer participate in this forum") if user.banned_from?(forum)
  end
  
  def update_ranking
    if votes_point <= 0
      self.update_attribute :ranking, votes_point
    else
      self.update_attribute :ranking, ci_lower_bound(up_votes_count, votes_count)
    end
    reorder
  end
  
  # http://www.evanmiller.org/how-not-to-sort-by-average-rating.html
  def ci_lower_bound(pos, n, confidence=0.95)
    return 0 if n == 0
    z = 1.96 # Statistics2.pnormaldist(1-(1-confidence)/2)
    phat = 1.0*pos/n
    (phat + z*z/(2*n) - z * Math.sqrt((phat*(1-phat)+z*z/(4*n))/n))/(1+z*z/n)
  end
  
  # insertion sort to fixed the nested set when ranking changes
  def reorder
    sibs = siblings
    return if sibs.empty?
    sibs.each do |s|
      if self.ranking >= s.ranking
        self.move_to_left_of(s) and return
      end
    end
    self.move_to_right_of(sibs.last)
  end
end

app/controllers/account/comments_controller.rb
class Account::CommentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :require_current_forum!
  
  def index
    @comments = Comment.where(:forum_id => current_forum.id, :user_id => current_user.id)
      .includes(:post, :user)
      .desc(:created_at)
      .page(params[:page])
  end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :require_current_forum!
  before_filter :authenticate_user!
  before_filter :load_params
  
  def load_params
    @post = current_forum.posts.find(params[:post_id])
    @comment = @post.comments.find(params[:id]) if params[:id].present?
  end
  
  def create
    @comment = @post.comments.new(params[:comment])
    @comment.forum = current_forum
    @comment.user = current_user
    @comment.parent = @post.comments.find(params[:comment][:parent_id]) unless params[:comment][:parent_id].blank?
    
    respond_to do |format|
      format.html do
        if @comment.save
          redirect_to post_path(@comment.post), :notice => "Comment posted!"
        else
          redirect_to post_path(@comment.post)
        end
      end
      format.js
    end
  end
  
  def update
    authorize! :update, @comment
    if @comment.update_attributes(params[:comment])
      redirect_to post_path(@post), :notice => "Updated!"
    else
      render :edit
    end
  end
  
  def edit
    authorize! :edit, @comment
  end
  
  def destroy
    if @comment.children.empty? or current_user.admin_of?(@comment.forum)
      @comment.destroy
    else
      @comment.update_attribute :deleted, true
    end
    redirect_to @post, :notice => "#{current_forum.comment_label} deleted"
  end
end

app/helpers/account/comments_helper.rb
module Account::CommentsHelper
end

app/views/comments/_comment.html.erb
<%
  indent            = true  if local_assigns[:indent].nil?
  show_post_link    = false if local_assigns[:show_post_link].nil?
  show_links        = true  if local_assigns[:show_links].nil?
  voting            = true  if local_assigns[:voting].nil?
%>

<div class="comment <%= comment_offset(comment.depth) if indent %>" id="<%= dom_id(comment) %>">
  <div class="show">
    <%= render :partial => 'shared/byline', :locals => {:comment_or_post => comment, :show_post_link => show_post_link, :voting => voting} %>
  
    <% if comment.deleted %>
      <p><small>[deleted]</small></p>
    <% else %>
      <%= comment.html.html_safe %>
  
      <% if show_links %>
        <p>
          <%= link_to 'reply', '#', :class => "reply-link" %>
          <% if can? :edit, comment %>
            <%= link_to 'edit', edit_post_comment_path(@post, comment) %>
          <% end %>
          <% if can? :destroy, comment %>
            <%= link_to 'delete', post_comment_path(@post, comment), :method => :delete, :confirm => "Are you sure you want to delete this #{current_forum.comment_label.downcase}?" %>
          <% end %>
        </p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<% reply_comment ||= false %>

<%= form_for [@post,@comment], :remote => reply_comment, :html => {:class => "comment-form"} do |f| %>
  <%= f.hidden_field :parent_id %>
  
  <%= render 'shared/error_messages', :target => @post %>
  <%= render 'shared/error_messages', :target => @comment %>
  
  <p><%= f.text_area :text, :class => "span8" %></p>
  <p>
    <% button_text = @comment.new_record? ? current_forum.new_comment_label : 'Save Changes' %>
    <%= submit_tag button_text, :class => "btn btn-primary", :disable_with => button_text, :disabled => !signed_in? %>
    
    <% if reply_comment %>
      <%= link_to "cancel", '#', :class => "cancel-link btn" %>
    <% end %>
    
    <% if not signed_in? %>
      <%= link_to "Sign in or create an account", signin_path %> to discuss.
    <% end %>
  </p>
<% end %>

app/views/comments/create.js.erb
$('#comment_<%= @comment.parent.id %> form').remove();
<% if @comment.save %>
  $('#comment_<%= @comment.parent.id %>').after("<%= escape_javascript(render @comment) %>");
<% end %>