config/routes.rb
Ribbot::Application.routes.draw do

  resources :posts do
    resources :comments
  end
  resources :forums
  resources :votes
  resources :users do
    member do
      put :password_reset
    end
    collection do
      post :create_with_forum
    end
  end
  resources :participations do
    member do
      put :ban
      put :unban
      put :hide
    end
  end
  resources :themes
  resources :pages
  
  namespace :account do
    resources :comments
    resources :posts
    resource  :profile
    resources :users
    resources :settings
    resources :tags do
      post :sort, :on => :collection
    end
    resources :pages do
      post :sort, :on => :collection
    end
    resources :themes do
      post :install, :on => :member
      post :uninstall, :on => :collection
    end
    resource :ownership
    resource :domain
  end
  
  namespace :superuser do
    resources :forums
  end
  
  resources :verifications
  resources :password_resets
  resources :sessions

  match 'signin' => "sessions#new"
  match 'signout' => "sessions#destroy", :via => :delete
  match 'features' => 'static#features'
  match 'pricing' => 'static#pricing'
  
  constraints(Subdomain) do
    match '/' => 'posts#index'  
  end
  
  root :to => 'users#new'
  

end

app/views/shared/_ads.html.erb
<%
  show = true
  show = false if Rails.env.test?
  show = @posts.size > 5 rescue show
  show = @posts.results.size > 5 rescue show
  show = @comments.size > 5 rescue show
%>

<% if show %>
  <script type="text/javascript"><!--
  google_ad_client = "ca-pub-7721655128098525";
  /* Ribbot sidebar */
  google_ad_slot = "4667431976";
  google_ad_width = 200;
  google_ad_height = 200;
  //-->
  </script>
  <script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
  </script>
<% end %>

app/views/shared/_byline.html.erb
<%
  show_post_link     = false if local_assigns[:show_post_link].nil?
  voting             = false if local_assigns[:voting].nil?
  show_tags          = false if local_assigns[:show_tags].nil?
  show_comments_link = false if local_assigns[:show_comments_link].nil?
%>

<p class="byline">
  <%= render :partial => 'votes/vote', :locals => {:voteable => comment_or_post} if voting %>
  
  <span class='points'><%= comment_or_post.votes_point %></span> point<%= 's' unless comment_or_post.votes_point == 1 %>
  
  by <%= link_to image_tag(comment_or_post.user.gravatar_url), comment_or_post.user %> 
  
  <%= link_to comment_or_post.user.name, comment_or_post.user, :class => "user-link" %> <%= time_ago_in_words comment_or_post.created_at %> ago
  
  <% if show_post_link %>
    <% if comment_or_post.is_a?(Comment) %>
      on <%= link_to comment_or_post.post.title, comment_or_post.post %>
    <% elsif comment_or_post.is_a?(Post) %>
    on <%= link_to comment_or_post.title, comment_or_post %>
    <% end %>
  <% end %>
  
  <%= comment_or_post.ranking.round(6) if params[:ranking].present? %>
  
  <% if show_comments_link and comment_or_post.is_a?(Post) %>
    with <%= link_to pluralize(comment_or_post.comment_count, 'comment'), post_path(comment_or_post) %>
  <% end %>
  
  <% if show_tags and comment_or_post.is_a?(Post) %>
    <% comment_or_post.tags.each do |t| %>
      <%= link_to t.name, root_path(:tags => t.name), :class => "tag" %>
    <% end %>
  <% end %>
</p>

app/views/shared/_error_messages.html.erb
<% if(target.errors.any? rescue false) %>
  <div class="alert">
    <% target.errors.full_messages.each do |msg| %>
      <%= msg %><br/>
    <% end %>
  </div>
<% end %>

app/views/shared/_flashy.html.erb
<% if flash.present? %>
  <div class="container flash">
    <% flash.each do |type, msg| %>
      <%= content_tag :div, :class => "alert #{flash_type_to_css_class type}" do %>
        <a class="close">×</a>
        <%= msg %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="span3">
  <ul class="nav nav-list well">
    <li class="<%= 'active' if controller_name == 'comments' %>"><%= link_to current_forum.comments_label, account_comments_path %></li>
    <li class="<%= 'active' if controller_name == 'posts' %>"><%= link_to current_forum.posts_label, account_posts_path %></li>
    <li class="<%= 'active' if controller_name == 'profiles' %>"><%= link_to 'Profile', account_profile_path %></li>

    <% if can? :edit, current_forum %>
      <li class="divider"></li>
      <li class="nav-header">Admin Options</li>
      <li class="<%= 'active' if controller_name == 'settings' %>"><%= link_to "Settings", account_settings_path %></li>
      <li class="<%= 'active' if controller_name == 'users' %>"><%= link_to "Users", account_users_path %></li>
      <li class="<%= 'active' if controller_name == 'tags' %>"><%= link_to "Tags", account_tags_path %></li>
      <li class="<%= 'active' if controller_name == 'pages' %>"><%= link_to "Pages", account_pages_path %></li>
      <li class="<%= 'active' if controller_name == 'themes' %>"><%= link_to "Themes", account_themes_path %></li>
      <% if current_user.owner_of?(current_forum) %>
        <li class="<%= 'active' if controller_name == 'ownerhip' %>"><%= link_to "Ownership", account_ownership_path %></li>
        <li class="<%= 'active' if controller_name == 'domain' %>"><%= link_to "Domain", account_domain_path %></li>
      <% end %>
    <% end %>
  </ul>
  <br/>
</div>

app/views/shared/_superuser_tabs.html.erb
<ul class="nav nav-tabs">
  <li class="<%= 'active' if controller_name == 'forums' %>"><%= link_to "Forums", superuser_forums_path %></li>
</ul>

app/views/shared/_tags.html.erb
<% if current_forum.tags.present? %>
  <h6>Filter By Tags</h6>
  
  <% current_names = params[:tags].split(',') rescue [] %>
  <% current_forum.tags.each do |t| %>
    <% if current_names.include?(t.name) %>
      <%= tag_link t, true %>
    <% else %>
      <%= tag_link t %>
    <% end %>
  <% end %>
<% end %>