config/routes.rb
Ribbot::Application.routes.draw do

  resources :posts do
    resources :comments
  end
  resources :forums
  resources :votes
  resources :users do
    member do
      put :password_reset
    end
    collection do
      post :create_with_forum
    end
  end
  resources :participations do
    member do
      put :ban
      put :unban
      put :hide
    end
  end
  resources :themes
  resources :pages
  
  namespace :account do
    resources :comments
    resources :posts
    resource  :profile
    resources :users
    resources :settings
    resources :tags do
      post :sort, :on => :collection
    end
    resources :pages do
      post :sort, :on => :collection
    end
    resources :themes do
      post :install, :on => :member
      post :uninstall, :on => :collection
    end
    resource :ownership
    resource :domain
  end
  
  namespace :superuser do
    resources :forums
  end
  
  resources :verifications
  resources :password_resets
  resources :sessions

  match 'signin' => "sessions#new"
  match 'signout' => "sessions#destroy", :via => :delete
  match 'features' => 'static#features'
  match 'pricing' => 'static#pricing'
  
  constraints(Subdomain) do
    match '/' => 'posts#index'  
  end
  
  root :to => 'users#new'
  

end

app/models/forum.rb
class Forum
  include Mongoid::Document
  include Mongoid::Timestamps
  
  POST_OPTIONS = {
    text_or_url: 0,
    url_or_text: 1,
    text_only:   2,
    url_only:    3
  }
  
  field :subdomain, type: String
  field :name, type: String
  field :description, type: String
  field :custom_domain, type: String
  
  field :post_options, type: Integer, default: POST_OPTIONS[:text_or_url]
  
  field :post_label, type: String, default: "Post"
  field :posts_label, type: String, default: "Posts"
  field :new_post_label, type: String, default: "New Post"
  field :comment_label, type: String, default: "Comment"
  field :comments_label, type: String, default: "Comments"
  field :new_comment_label, type: String, default: "Add Comment"
  
  index :subdomain, unique: true
  index :custom_domain
  
  has_many :posts
  has_many :participations, :dependent => :destroy
  has_many :tags
  has_many :pages
  belongs_to :theme
  
  validates_presence_of :subdomain, :name
  validates_uniqueness_of :subdomain, :case_sensitive => false
  validates_uniqueness_of :custom_domain, :case_sensitive => false, :allow_blank => true
  validate :subdomain_uses_valid_characters
  validate :subdomain_uses_valid_name
  
  before_validation :set_default_name
  before_save :clean_params
  before_save :add_or_remove_custom_domain
  
  def subdomain_uses_valid_characters
    errors.add(:subdomain, "can only use numbers and letters") if subdomain =~ /[^a-z0-9\-]/i
  end
  
  def custom_domain_uses_valid_characters
    if custom_domain.present? and (custom_domain =~ /[^a-z0-9\-\.]/i or custom_domain =~ /ribbot\.com/i)
      errors.add(:custom_domain, "should be in the format www.example.com or forum.example.com")
    end
  end
  
  def subdomain_uses_valid_name
    errors.add(:subdomain, "is already taken") if ['blog','legal','www','help','contact','jobs','about','proxy'].include?(subdomain.downcase)
  end
  
  def add_or_remove_custom_domain
    if custom_domain_changed? and Rails.env.production?
      heroku_client = Heroku::Client.new(ENV['HEROKU_USER'], ENV['HEROKU_API_KEY'])
      heroku_client.remove_domain('ribbot', custom_domain_was) if custom_domain_was.present?
      heroku_client.add_domain('ribbot', custom_domain) if custom_domain.present?
    end
  end
  
  def set_default_name
    if name.blank?
      self.name = subdomain.titleize
    end
  end
  
  def add_member user
    if p = participations.where(:user_id => user.id).first
      p.update_attribute :hidden, false if p.hidden?
    else
      participations.create!(:user => user, :level => Participation::MEMBER)
    end
  end
  
  def add_admin user
    participations.create!(:user => user, :level => Participation::ADMIN)
  end
  
  def add_owner user
    participations.create!(:user => user, :level => Participation::OWNER)
  end
  
  def clean_params
    self.subdomain = subdomain.downcase
    self.custom_domain = custom_domain.downcase if custom_domain.present?
  end
  
  def hostname
    if custom_domain.present?
      custom_domain
    else
      subdomain+"."+Ribbot::Application.config.action_mailer.default_url_options[:host]
    end
  end
end

app/models/post.rb
require 'uri'

class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  include Sunspot::Mongoid
  include Mongo::Voteable
  include GravityRanking
  include MarkdownProcessor
  
  field :title, type: String
  field :url, type: String, index: true
  field :text, type: String
  field :html, type: String
  field :ranking, type: Float, default: 0.0
  field :comment_count, type: Integer, default: 0
  
  index :ranking
  index :'votes.point'

  belongs_to :user, index: true
  belongs_to :forum, index: true
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :tags, inverse_of: nil, index: true

  validates_presence_of :title, :user, :forum
  validate :user_is_not_banned
  validate :url_is_new
  validate :presence_of_url_or_text
  validate :format_of_url
  
  voteable self, :up => +1, :down => -1
  
  before_save   :process_markdown
  after_create  :create_participation
  after_save    :update_post_counts
  after_destroy :update_post_counts
  
  searchable do
    text :title, :boost => 2.0, :stored => true
    text :url, :stored => true
    text :text, :stored => true
    text :comments_texts do
      comments.collect {|c| c.text }
    end
    string :forum_id, :references => Forum
    string :tag_ids, :multiple => true
  end
  
  def create_participation
    forum.add_member(user)
  end
  
  def user_is_not_banned
    errors.add(:base, "You can no longer participate in this forum") if user.banned_from?(forum)
  end
  
  def url_is_new
    if self.url.present?
      self.url = self.url.downcase
      if post = forum.posts.where(:url => self.url, :created_at.gt => 2.months.ago).first
        errors.add(:base, "That URL has already been submitted") unless post == self
      end
    end
  end
  
  def presence_of_url_or_text
    if self.url.blank? and self.text.blank?
      errors.add(:base, "Post can't be blank")
    end
  end
  
  def format_of_url
    if self.url.present?
      errors.add(:base, "Invalid URL") unless self.url =~ URI::regexp
    end
  end
  
  def update_post_counts
    if tag_ids_changed?
      tags.each do |t|
        t.update_attribute :posts_count, Post.all_in(:tag_ids => [t.id]).count
      end
    end
  end
  
  def self.with_tags names, forum
    if names.blank?
      scoped
    else
      names = names.split(',')
      tags = forum.tags.all_in(:name => names)
      all_in(:tag_ids => tags.collect{|t| t.id})
    end
  end
  
end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :require_current_forum!
  
  def index
    @posts = Post.where(:forum_id => current_forum.id, :user_id => current_user.id)
      .includes(:post, :user)
      .desc(:created_at)
      .page(params[:page])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_current_forum!
  before_filter :authenticate_user!, :except => [:show, :index]
  
  def new
    @post = Post.new
  end
  
  def create
    @post = current_forum.posts.new(params[:post])
    @post.user = current_user
    @post.forum = current_forum
    if @post.save
      current_user.vote(@post, :up)
      @post.update_ranking
      redirect_to @post, :notice => "#{current_forum.post_label} created!"
    else
      render :new
    end
  end
  
  def index
    if params[:search].present?
      @posts = Post.solr_search do
        keywords params[:search]
        with :forum_id, current_forum.id
        paginate :page => params[:page]
      end
    else
      @posts = current_forum.posts.with_tags(params[:tags], current_forum).where(:'votes.point'.gt => -5).page(params[:page])
      
      if params[:sort] == 'top'
        @posts = @posts.desc('votes.point')
      elsif params[:sort] == 'latest'
        @posts = @posts.desc(:created_at)
      else
        @posts = @posts.desc(:ranking)
      end            
    end
  end
  
  def show
    @post = current_forum.posts.where(:_id =>params[:id]).first
    if @post.nil?
      redirect_to root_path(:subdomain => current_forum.subdomain), :notice => "That post is no longer available."
      return
    end
    @comment = @post.comments.new
    @comments = @post.comments.asc(:lft).where(:'votes.point'.gt => -5).page(params[:page])
  end
  
  def edit
    @post = current_forum.posts.find(params[:id])
    authorize! :edit, @post
  end
  
  def update
    params[:post][:tag_ids] ||= []
    @post = current_forum.posts.find(params[:id])
    authorize! :update, @post
    if @post.update_attributes(params[:post])
      redirect_to @post, :notice => "Post updated!"
    else
      render :edit
    end
  end
  
  def destroy
    @post = current_forum.posts.find(params[:id])
    authorize! :destroy, @post
    @post.destroy
    redirect_to root_path, :notice => "Post deleted!"
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/posts/_form.html.erb
<%= form_for @post, :html => {:class => "post-form form-stacked"} do |f| %>
  <h2><%= current_forum.new_post_label %></h2><br/>
  
  <%= render 'shared/error_messages', :target => @post %>
  
  <p>
    <%= f.label :title %>
    <%= f.text_field :title, :class => "span8" %>
  </p>
  
  <p>
    <% if current_forum.post_options == Forum::POST_OPTIONS[:text_or_url] %>
      <%= link_to 'Text', '#', :class => 'text-link active' %> or <%= link_to 'URL', '#', :class => 'url-link' %><br/>
      <%= f.text_field :url, :placeholder => 'http://', :class => "span8", :style => "display: none;" %>
      <%= f.text_area :text, :class => "span8" %>
    <% elsif current_forum.post_options == Forum::POST_OPTIONS[:url_or_text] %>
      <%= link_to 'URL', '#', :class => 'url-link active' %> or <%= link_to 'Text', '#', :class => 'text-link' %><br/>
      <%= f.text_field :url, :placeholder => 'http://', :class => "span8" %>
      <%= f.text_area :text, :class => "span8", :style => "display: none;" %>
    <% elsif current_forum.post_options == Forum::POST_OPTIONS[:url_only] %>
      <%= f.label :url, 'URL' %>
      <%= f.text_field :url, :placeholder => 'http://', :class => "span8" %>
    <% elsif current_forum.post_options == Forum::POST_OPTIONS[:text_only] %>
      <%= f.label :text %>
      <%= f.text_area :text, :class => "span8" %>
    <% end %>
  </p>
  
  <% if current_forum.tags.present? %>
    <p>
      <%= f.label :tag_ids, 'Tags' %>
      <% current_forum.tags.each do |tag| %>
        <span>
          <% on = @post.tags.include?(tag) %>
          <%= check_box_tag "post[tag_ids][]", tag.id, on, :class => "tag-checkbox" %>
          <%= link_to tag.name, '#', :class => "tag #{'active' if on} tag-link" %>
        </span>
      <% end %>
    </p>
  <% end %>
  
  <div class="form-actions">
    <% if @post.new_record? %>
      <%= submit_tag "Submit", :class => "btn btn-primary", :disable_with => "Submitting..." %> &nbsp; <%= link_to "Cancel", :back, :class => "btn" %>
    <% else %>
      <%= submit_tag "Save Changes", :class => "btn btn-primary", :disable_with => "Saving..." %> &nbsp; <%= link_to "Cancel", :back, :class => "btn" %>
    <% end %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<%
  voting = true if local_assigns[:voting].nil?
%>

<tr class="post" id="<%= dom_id(post) %>">
  <% if voting %>
    <td>
      <%= render :partial => 'votes/vote', :locals => {:voteable => post} %>
    </td>
  <% end %>
    
  <td class="description">
    <div class="pull-right">
      <% post.tags.each do |t| %>
        <%= tag_link t %>
      <% end %>
    </div>
    <% if post.url.present? %>
      <%= link_to post.title, post.url, :rel => 'nofollow', :class => 'post-link' %>
    <% else %>
      <%= link_to post.title, post, :class => 'post-link' %>
    <% end %>
    <%= render :partial => 'shared/byline', :locals => {:comment_or_post => post, :show_comments_link => true} %>
  </td>
</tr>

app/views/posts/index.html.erb
<div class="row">
  <div class="span9">
    
    <%= link_to current_forum.new_post_label, new_post_path, :class => "btn btn-primary pull-right" %>
    <%= form_tag posts_path, :method => :get, :class => 'form-inline' do %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :class => "btn", :disable_with => "Search" %>
      <% if params[:search].present? %>
        &nbsp;<%= link_to 'clear', root_path %>
      <% end %>
    <% end %>
    
    <% if @posts.empty? and current_forum.posts.empty? %>
      <div class="alert-message block-message success">
        <p><strong>Welcome! This is a brand new forum</strong></p>
        <p>To get started try adding the first <%= current_forum.post_label.downcase %>.</p>
        <div class="alert-actions">
          <%= link_to current_forum.new_post_label, new_post_path, :class => "btn" %>
        </div>
      </div>
    <% elsif @posts.empty? %>
      <div class="alert-message block-message info no-results">
        <p><strong>Your search didn't return an results!</strong></p>
        <p>Please try a new search or <%= link_to 'go back', root_path %>.</p>
      </div>
    <% else %>
      
    <% if params[:search].present? %>
      <table class="table table-striped">
        <%= render @posts.results %>
      </table>
    <% else %>
      <ul class="nav nav-tabs">
        <li class="<%= 'active' if params[:sort].blank? %>"><%= link_to 'Popular', posts_path(request.query_parameters.merge(:sort => nil)) %></li>
        <li class="<%= 'active' if params[:sort] == 'top' %>"><%= link_to 'Top', posts_path(request.query_parameters.merge(:sort => 'top')) %></li>
        <li class="<%= 'active' if params[:sort] == 'latest' %>"><%= link_to 'Latest', posts_path(request.query_parameters.merge(:sort => 'latest')) %></li>
      </ul>
      <table class="table table-striped">
        <%= render @posts %>
      </table>
    <% end %>
      
      <%= paginate @posts %>
    <% end %>
  </div>
  <div class="span3" style="padding-top: 68px;">
    <%= render 'shared/tags' %>
    <br/><br/>
    <%= render 'shared/ads' %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="post" id="<%= dom_id(@post) %>">
  <% if @post.url.present? %>
    <h2><%= link_to @post.title, @post.url, :rel => 'nofollow'%></h2>
  <% else %>
    <h2><%= @post.title %></h2>
  <% end %>
  
  <%= render :partial => 'shared/byline', :locals => {:comment_or_post => @post, :voting => true, :show_tags => true} %>
  <%= @post.html.html_safe if @post.html.present? %>
  <p>
    <% if can? :edit, @post %>
      <%= link_to 'edit', edit_post_path(@post) %>
    <% end %>
    <% if can? :destroy, @post %>
      <%= link_to 'delete', post_path(@post), :method => :delete, :confirm => "Are you really sure you want to delete this post?  This will delete any comments as well." %>
    <% end %>
  </p>
</div>

<hr/>

<div class="pull-right">
  <%= render 'shared/ads' %>
</div>

<%= render "comments/form" %>

<%= render @comments %>

<div id="reply_comment" style="display: none;">
  <%= render :partial => "comments/form", :locals => {:reply_comment => true} %>
</div>


<%= paginate @comments %>