config/routes.rb
Ribbot::Application.routes.draw do

  resources :posts do
    resources :comments
  end
  resources :forums
  resources :votes
  resources :users do
    member do
      put :password_reset
    end
    collection do
      post :create_with_forum
    end
  end
  resources :participations do
    member do
      put :ban
      put :unban
      put :hide
    end
  end
  resources :themes
  resources :pages
  
  namespace :account do
    resources :comments
    resources :posts
    resource  :profile
    resources :users
    resources :settings
    resources :tags do
      post :sort, :on => :collection
    end
    resources :pages do
      post :sort, :on => :collection
    end
    resources :themes do
      post :install, :on => :member
      post :uninstall, :on => :collection
    end
    resource :ownership
    resource :domain
  end
  
  namespace :superuser do
    resources :forums
  end
  
  resources :verifications
  resources :password_resets
  resources :sessions

  match 'signin' => "sessions#new"
  match 'signout' => "sessions#destroy", :via => :delete
  match 'features' => 'static#features'
  match 'pricing' => 'static#pricing'
  
  constraints(Subdomain) do
    match '/' => 'posts#index'  
  end
  
  root :to => 'users#new'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <meta name="Description" content="<%= meta_description %>">
  <link rel="shortcut icon" href="/favicon.ico" />
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag theme_path(current_theme) if current_theme.present? %>
  

  <%= csrf_meta_tags %>
  <%= analytics_code %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
  <% if current_user and current_user.superuser? %>
    <div class="admin-link">
      <%= link_to "Admin", superuser_forums_path %>
    </div>
  <% end %>
  
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        
        <%= link_to site_name, root_path, :class => "brand" %>
        
        <div class="nav-collapse">
          <% if current_forum.nil? %>
            <ul class="nav">
              <li class="<%= 'active' if action_name == 'features' %>"><%= link_to 'Features', features_path %></li>
              <li class="<%= 'active' if action_name == 'pricing' %>"><%= link_to 'Pricing', pricing_path %></li>
              <li><%= link_to 'Support', root_url(:subdomain => 'support')%></li>
            </ul>
          <% else %>
            <ul class="nav">
              <%= render 'pages/header' %>
            </ul>
          <% end %>
          
          <ul class="nav pull-right">
            <% if signed_in? %>
              <% if current_forum %>
                <li class="dropdown" data-dropdown="dropdown">              
                  <%= link_to "#{current_user.name} <b class='caret'></b>".html_safe, '#', :class => "dropdown-toggle", :'data-toggle' => 'dropdown' %>
                  <ul class="dropdown-menu">
                    <li><%= link_to "My Profile", account_comments_path %></li>
                    <% if can? :edit, current_forum %>
                      <li><%= link_to "Forum Settings", account_settings_path %></li>
                    <% end %>
                    <li><%= link_to "Leave Forum", forums_url(:subdomain => false) %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Sign Out", signout_path, :method => :delete %></li>
                  </ul>
                </li>
              <% else %>
                <li class="<%= 'active' if controller_name == 'forums' %>"><%= link_to "My Forums", forums_path %></li>
                <li><%= link_to "Sign Out", signout_path, :method => :delete %></li>
              <% end %>
            <% else %>
              <li class="<%= "active" if signin_active? %>"><%= link_to "Sign In or Sign Up", signin_path %></li>

            <% end %>
          </ul>

        </div>
      </div>
    </div>
  </div>

  <%= render 'shared/flashy' %>
  
  <div class="container">
    <% if @sidebar %>    
      <div class="page-header">
        <h1><%= current_forum.name %> <small><%= current_forum.slogan %></small></h1>
      </div>
      <div class="row">
        <%= render 'shared/sidebar' %>
        <div class="span10">
          <%= yield %>
        </div>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
    
    <footer>
      <% if request.subdomain.present? and request.subdomain != 'www' %>
        <p class='pull-right'>
          Powered by 
          <% if Rails.env.production? %>
            <%= link_to "Ribbot.com", "http://ribbot.com" %>
          <% else %>
            <%= link_to "Ribbot.com", "http://ribbot.local:3000" %>
          <% end %>
        </p>
      <% else %>
        <p>&copy; Ribbot <%= Time.now.year %></p>
      <% end %>
    </footer>
  </div>
  
  <%= javascript_include_tag "application" %>
  
  <script type="text/javascript">
    $(document).ready(function() {
      <%= yield :javascript_footer %>
    });
  </script>
</body>
</html>